# Site settings
title: Semantic Data Enrichment for Data Scientists
# email: your-email@domain.com
url: https://ew-shopp.github.io/eswc2019-tutorial/
description: "Tutorial website for the ESWC2019 tutorial on semantic data enrichment for data scientists."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Build settings
markdown: kramdown
permalink: pretty
